name: Makefile CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - name: configure
    #   run: ./configure

    - name: Install dependencies
      run: sudo apt-get -y install protobuf-compiler
      
    - name: Build plugin
      run: make check

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
