name: CI (main)
run-name: Unit tests (main)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.4

    - name: Install dependencies
      run: sudo apt-get -y install protobuf-compiler

    - name: Build plugin
      run: make plugin

    - name: Run unit tests
      run: make test
